# LaboratoryTask5

**Jade Natasha S. Ragot**

**DS4A**

**Laboratory Task 5**

*(02_PyTorch Basics)*

**1. Perform Standard Imports**

In [1]:
import torch
import numpy as np

**2. Create a function called `set_seed()` that accepts `seed: int` as a parameter, this function must return nothing but just set the seed to a certain value.**

Without this, random functions give different results every time we try to run the code. Setting a seed makes randomness reproducible — same seed always produces the same "random" numbers.

In [2]:
def set_seed(seed):
    np.random.seed(seed)
    torch.manual_seed(seed)

**3. Create a NumPy array called "arr" that contains 6 random integers between 0 (inclusive) and 5 (exclusive), call the `set_seed()` function and use `42` as the seed parameter.**

In [4]:
set_seed(42)
arr = np.random.randint(0, 5, size=6).astype('int32') # generates 6 random integers from 0 up to (but not included) 5

assert np.array_equal(arr, np.array([3,4,2,4,4,1])), "Oops"
print(arr)

[3 4 2 4 4 1]


**4. Create a tensor "x" from the array above**

In [5]:
x = torch.from_numpy(arr)

**5. Change the dtype of x from `int32` to `int64`**

In [6]:
print('Old:', x.type())

x = x.type(torch.int64)

print('New:', x.type())

Old: torch.IntTensor
New: torch.LongTensor


6. Reshape `x` into a 3x2 tensor
There are several ways to do this.

In [8]:
x = x.reshape(3,2)
print (x)

tensor([[3, 4],
        [2, 4],
        [4, 1]])


**7. Return the right-hand column of tensor `x`**

In [9]:
print(x[:,1:])

tensor([[4],
        [4],
        [1]])


**8. Without changing x, return a tensor of square values of `x`**

There are several ways to do this.

`x.pow(2)` calculates the squares and returns a new tensor — but since nothing captures that return value, it's discarded, and `print(x)` just prints the original, unsquared `x`. So this technically satisfies not chaning the `x` but it never actually shows the squared values.

In [10]:
sqrd = x.pow(2)
print(sqrd)
print(x)

tensor([[ 9, 16],
        [ 4, 16],
        [16,  1]])
tensor([[3, 4],
        [2, 4],
        [4, 1]])


**9. Create a tensor `y` with the same number of elements as `x`, that can be matrix-multiplied with `x`**

Use PyTorch directly (not NumPy) to create a tensor of random integers between 0 (inclusive) and 5 (exclusive). Use 42 as seed.
Think about what shape it should have to permit matrix multiplication.

In [12]:
set_seed(42)
y = torch.randint(0,5,(2,3))

assert torch.equal(y, torch.tensor([[2, 2, 1],[4, 1, 0]])), "Oops"
print(y)

tensor([[2, 2, 1],
        [4, 1, 0]])


**10. Find the matrix product of `x` and `y`.**

In [13]:
prod = torch.mm(x,y)
prod

tensor([[22, 10,  3],
        [20,  8,  2],
        [12,  9,  4]])

This Laboratory Task builds the tensor fluency (creation, reshaping, indexing, dtype handling, and multiplication) that underlies every neural network operation covered in previous tasks.