In [1]:
import torch
import numpy as np

In [2]:
def set_seed(seed):
    np.random.seed(seed)
    torch.manual_seed(seed)

In [3]:
set_seed(42)
arr = np.random.randint(0, 5, size=6).astype('int32') # generates 6 random integers from 0 up to (but not included) 5

assert np.array_equal(arr, np.array([3,4,2,4,4,1])), "Oops"
print(arr)

[3 4 2 4 4 1]


In [4]:
x = torch.from_numpy(arr)

In [5]:
print('Old:', x.type())

x = x.type(torch.int64)

print('New:', x.type())

Old: torch.IntTensor
New: torch.LongTensor


In [6]:
x = x.reshape(3,2)
print (x)

tensor([[3, 4],
        [2, 4],
        [4, 1]])


In [7]:
print(x[:,1:])

tensor([[4],
        [4],
        [1]])


In [8]:
sqrd = x.pow(2)
print(sqrd)
print(x)

tensor([[ 9, 16],
        [ 4, 16],
        [16,  1]])
tensor([[3, 4],
        [2, 4],
        [4, 1]])


In [9]:
set_seed(42)
y = torch.randint(0,5,(2,3))

assert torch.equal(y, torch.tensor([[2, 2, 1],[4, 1, 0]])), "Oops"
print(y)

tensor([[2, 2, 1],
        [4, 1, 0]])


In [10]:
prod = torch.mm(x,y)
prod

tensor([[22, 10,  3],
        [20,  8,  2],
        [12,  9,  4]])